### ISSUE TITLE
video / animated gif / working demo of effect

### ISSUE THREAD

**Issue by deanmalmgren** [clarkmalmgren/angular-onselect#1]
You have a great description in the README, but it'd be pretty awesome to see what this kickass package does!

**Comment by clarkmalmgren** [comment]
@deanmalmgren, I was actually planning on moving the contents of /example into github pages and having a live demo instead.  Thoughts?

**Comment by deanmalmgren** [comment]
in my experience [[citation](http://deanmalmgren.github.io/catcorrjs/)], `gh-pages` is meh, ok. i personally prefer readthedocs so you can maintain the documentation in the same branch as the source code. this is particularly convenient for versioning your documentation alongside your source code

**Comment by clarkmalmgren** [comment]
I started to look at readthedocs.  Looks... involved.

I know that gh-pages aren't necessarily as pretty, but really, I just want a place to host the already written HTML an JS file.  I'm open to a PR or a lesson in creating the documentation.

**Comment by deanmalmgren** [comment]
nice!
