### ISSUE TITLE
example not working after following contributing guidelines

### ISSUE THREAD

**Issue by deanmalmgren** [clarkmalmgren/angular-onselect#11]
is it possible that there's a problem in angular?

<img width="1276" alt="screen shot 2015-11-06 at 9 16 49 am" src="https://cloud.githubusercontent.com/assets/255672/11000398/24bf0508-8467-11e5-864c-148a236a1221.png">

**Comment by clarkmalmgren** [comment]
It appears that angular failed to parse correctly for you which is highly suspect.

Did you by chance get a MD5 or SHA1 error when doing an npm install?

**Comment by clarkmalmgren** [comment]
Try deleting your `node_modules/angular` folder and running `npm install` again.  Should do the trick.  I just installed everything fresh and it is working for me.

_Don't you hate it when engineers say that?_

**Comment by deanmalmgren** [comment]
npm FTW. reinstalled angular and it was just fine.
