### ISSUE TITLE
n00b readable contributing guidelines

### ISSUE THREAD

**Issue by deanmalmgren** [clarkmalmgren/angular-onselect#2]
Starting from 
1. fork and clone the repository
2. npm install or some such thing
3. start a web server?

I'm not exactly sure what's involved here, but I'm a complete n00b that will actively contribute to this project if I can just figure out how to get started :)

**Comment by clarkmalmgren** [comment]
Sounds reasonable.  I'll create a CONTRIBUTING.md file to accompilish this.

**Comment by deanmalmgren** [comment]
on a related front, i'm guessing you want people to merge back into `develop` or into `master` when they submit PRs?

**Comment by clarkmalmgren** [comment]
I have been really used to using [git flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) although for this maybe we want to be using [forking workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow).

That would basically do away with the need for feature branches.  I still like the idea that master ALWAYS represents the latest release version and develop is pending but not yet released changes.

**Comment by deanmalmgren** [comment]
So long as you use [the AVH version of git flow](https://github.com/petervanderdoes/gitflow-avh), that sounds good to me. so new users should start feature branches with `git flow feature start <useful-title>` and then send a pull request to `develop`

**Comment by deanmalmgren** [comment]
I meant to add that the AVH version fixes a lot of rather annoying properties of the original git flow. For example, it always pulls the most recent version of branches that it is merging into.

**Comment by clarkmalmgren** [comment]
In the case of an external developer with a forked repository, there will really be two pull requests.  One from `feature/super-useful-title` to `develop` and then one from the `otherdude/develop` to `clarkmalmgren/develop`.  Seems excessive but maybe not.  It certainly would make sense for trusted developers who would be given write access to this repo directly.
