### ISSUE TITLE
Highlight across Complex DOM Structures

### ISSUE THREAD

**Issue by clarkmalmgren** [clarkmalmgren/angular-onselect#5]
Can't span complex DOM structures as it currently exists.  It doesn't even try, it just stops.

**Comment by deanmalmgren** [comment]
is the issue here that if you have text like:

```
<p>
  Hello Clark,
</p>
<p>
  My name is Dean.
</p>
```

and you select `Clark, My name`, then this is going across the close and start of new `<p>` elements?

**Comment by clarkmalmgren** [comment]
Well there is no way to highlight that well.  The problem is that 

``` html
<p>
  Hello <span class="os-highlight">Clark,
</p>
<p>
  My name</span> is Dean.
</p>
```

Isn't valid and so if you even try to do it using `Range.surroundContents()` when the range spans HTML nodes, it throws an Error.

**Comment by deanmalmgren** [comment]
It seems like this may need to be aware of the surrounding DOM elements. If it crosses a closing tag that hasn't been opened within the highlighted region, then it needs to close that `<span>` and start a new one. Not sure how tricky that is, but at least it would be valid HTML

**Comment by clarkmalmgren** [comment]
Yeah, that could happen.  It is a little more complicated than that though. This highly relies on the [Range](https://developer.mozilla.org/en-US/docs/Web/API/Range) object which only gives the start and end container.  So basically you have to walk the tree from sibling to sibling and up to parents as appropriate.  For instance, this one would be particularly awful:

``` html
<p>
  Hello <strong>Clark</strong>,
</p>
<p>
  <strike>Mi nombre es</strike> <span class="green"><strong>My name is</strong></span> Dean.
</p>
```

Where the highlight starts in the middle of "Hello" and ends in the middle of "My name is"...

**Comment by clarkmalmgren** [comment]
So this thread is actually two issues.  One is about how to author the highlighting surround block, the other about highlighting across complex DOM structures.  Since this is mostly about the complex DOM structures, I am going to edit some of the history and then create a separate issue for authoring of a surround block.

**Comment by deanmalmgren** [comment]
ahhhh, got it. OK, cool. Highlighting around complex DOM structures is
definitely tricky too (and, FWIW, probably not one we'll deal with in
scrubadub)

On Fri, Nov 6, 2015 at 1:05 PM Clark Malmgren notifications@github.com
wrote:

> So this thread is actually two issues. One is about how to author the
> highlighting surround block, the other about highlighting across complex
> DOM structures. Since this is mostly about the complex DOM structures, I am
> going to edit some of the history and then create a separate issue for
> authoring of a surround block.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/clarkmalmgren/angular-onselect/issues/5#issuecomment-154502842
> .
> 
> ## 

_dean malmgren | +1.312.884.9214 partner, data scientist | datascope_
